//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dilekce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dilekce()
        {
            this.Okundu = false;
        }
    
        public int DilekceId { get; set; }
        public string Baslik { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<bool> Okundu { get; set; }
    }
}
