//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Faturalar = new HashSet<Faturalar>();
        }
    
        public int KullaniciId { get; set; }
        public string TC { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public string Sifre { get; set; }
        public string Role { get; set; }
    
        public virtual Departman Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
    }
}
