//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class erp_KaderGUREntities : DbContext
    {
        public erp_KaderGUREntities()
            : base("name=erp_KaderGUREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<Dilekce> Dilekce { get; set; }
        public virtual DbSet<Faturalar> Faturalar { get; set; }
        public virtual DbSet<IsOrtaklari> IsOrtaklari { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
    
        public virtual int spIsOrtaklariSil(Nullable<int> isOrtaklariSil)
        {
            var isOrtaklariSilParameter = isOrtaklariSil.HasValue ?
                new ObjectParameter("IsOrtaklariSil", isOrtaklariSil) :
                new ObjectParameter("IsOrtaklariSil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIsOrtaklariSil", isOrtaklariSilParameter);
        }
    
        public virtual int spPersonelSil(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPersonelSil", idParameter);
        }
    }
}
