//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelId { get; set; }
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public Nullable<System.DateTime> iseGirisTarihi { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public Nullable<decimal> Maas { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
