//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Dil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Dil.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Kullanicilar {
            get {
                return ResourceManager.GetString("Kullanicilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finans.
        /// </summary>
        public static string KullanicilarF {
            get {
                return ResourceManager.GetString("KullanicilarF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        public static string KullanicilarIK {
            get {
                return ResourceManager.GetString("KullanicilarIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string KullanicilarIT {
            get {
                return ResourceManager.GetString("KullanicilarIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış &amp; Pazarlama.
        /// </summary>
        public static string KullanicilarSP {
            get {
                return ResourceManager.GetString("KullanicilarSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personeller.
        /// </summary>
        public static string Personeller {
            get {
                return ResourceManager.GetString("Personeller", resourceCulture);
            }
        }
    }
}
