//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Language.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        public static string Adet {
            get {
                return ResourceManager.GetString("Adet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string AdSoyad {
            get {
                return ResourceManager.GetString("AdSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Fiyat.
        /// </summary>
        public static string BirimFiyat {
            get {
                return ResourceManager.GetString("BirimFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciro.
        /// </summary>
        public static string Ciro {
            get {
                return ResourceManager.GetString("Ciro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman.
        /// </summary>
        public static string Departman {
            get {
                return ResourceManager.GetString("Departman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilekçeler.
        /// </summary>
        public static string Dilekceler {
            get {
                return ResourceManager.GetString("Dilekceler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string DogumTarihi {
            get {
                return ResourceManager.GetString("DogumTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        public static string Fatura {
            get {
                return ResourceManager.GetString("Fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Adedi.
        /// </summary>
        public static string FaturaAdedi {
            get {
                return ResourceManager.GetString("FaturaAdedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturalar.
        /// </summary>
        public static string Faturalar {
            get {
                return ResourceManager.GetString("Faturalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaları.
        /// </summary>
        public static string Faturalari {
            get {
                return ResourceManager.GetString("Faturalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura No.
        /// </summary>
        public static string FaturaNo {
            get {
                return ResourceManager.GetString("FaturaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Oluştur.
        /// </summary>
        public static string FaturaOlustur {
            get {
                return ResourceManager.GetString("FaturaOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Oluşturan.
        /// </summary>
        public static string FaturaOlusturan {
            get {
                return ResourceManager.GetString("FaturaOlusturan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        public static string FirmaAd {
            get {
                return ResourceManager.GetString("FirmaAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019 KaderGur Tüm Hakları Saklıdır.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string Guncelle {
            get {
                return ResourceManager.GetString("Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel Şifre.
        /// </summary>
        public static string GuncelSifre {
            get {
                return ResourceManager.GetString("GuncelSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün önce.
        /// </summary>
        public static string GunOnce {
            get {
                return ResourceManager.GetString("GunOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik.
        /// </summary>
        public static string Guvenlik {
            get {
                return ResourceManager.GetString("Guvenlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string Hakkında {
            get {
                return ResourceManager.GetString("Hakkında", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Iptal {
            get {
                return ResourceManager.GetString("Iptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşe Giriş Tarihi.
        /// </summary>
        public static string IseGirisTarihi {
            get {
                return ResourceManager.GetString("IseGirisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Islemler {
            get {
                return ResourceManager.GetString("Islemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Ortağı Ekle.
        /// </summary>
        public static string IsOrtagiEkleBaslik {
            get {
                return ResourceManager.GetString("IsOrtagiEkleBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Ortakları.
        /// </summary>
        public static string IsOrtaklari {
            get {
                return ResourceManager.GetString("IsOrtaklari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Kullanicilar {
            get {
                return ResourceManager.GetString("Kullanicilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler.
        /// </summary>
        public static string KullanicilarBaslik {
            get {
                return ResourceManager.GetString("KullanicilarBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finans.
        /// </summary>
        public static string KullanicilarF {
            get {
                return ResourceManager.GetString("KullanicilarF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        public static string KullanicilarIK {
            get {
                return ResourceManager.GetString("KullanicilarIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string KullanicilarIT {
            get {
                return ResourceManager.GetString("KullanicilarIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış &amp; Pazarlama.
        /// </summary>
        public static string KullanicilarSP {
            get {
                return ResourceManager.GetString("KullanicilarSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaş.
        /// </summary>
        public static string Maas {
            get {
                return ResourceManager.GetString("Maas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleyenler.
        /// </summary>
        public static string OnayBekleyen {
            get {
                return ResourceManager.GetString("OnayBekleyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string Onayla {
            get {
                return ResourceManager.GetString("Onayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Ekle.
        /// </summary>
        public static string PersonelEkle {
            get {
                return ResourceManager.GetString("PersonelEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personeller.
        /// </summary>
        public static string Personeller {
            get {
                return ResourceManager.GetString("Personeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Sayısı.
        /// </summary>
        public static string PersonelSayisi {
            get {
                return ResourceManager.GetString("PersonelSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili Düzenle.
        /// </summary>
        public static string ProfiliDuzenle {
            get {
                return ResourceManager.GetString("ProfiliDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yetkiniz henüz onaylanmamıştır lütfen (Admin)Bilgi İşlem departmanı ile iletişime geçiniz..
        /// </summary>
        public static string RolHatasi {
            get {
                return ResourceManager.GetString("RolHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı, .
        /// </summary>
        public static string RolUyarisi {
            get {
                return ResourceManager.GetString("RolUyarisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Adedi.
        /// </summary>
        public static string SatisAdedi {
            get {
                return ResourceManager.GetString("SatisAdedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Fiyat+KDV.
        /// </summary>
        public static string ToplamFiyatKDV {
            get {
                return ResourceManager.GetString("ToplamFiyatKDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string UrunAd {
            get {
                return ResourceManager.GetString("UrunAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni İş Ortağı.
        /// </summary>
        public static string YeniIsOrtagi {
            get {
                return ResourceManager.GetString("YeniIsOrtagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Personel.
        /// </summary>
        public static string YeniPersonel {
            get {
                return ResourceManager.GetString("YeniPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        public static string YeniSifre {
            get {
                return ResourceManager.GetString("YeniSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre Tekrar.
        /// </summary>
        public static string YeniSifreTekrar {
            get {
                return ResourceManager.GetString("YeniSifreTekrar", resourceCulture);
            }
        }
    }
}
